dermai:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: dermai
    username: root
    password: root
  redis:
    host: 121.199.44.1
    password: lsbshishabi123