server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
#  datasource:
#    druid:
#      driver-class-name: ${dermai.datasource.driver-class-name}
#      url: jdbc:mysql://${dermai.datasource.host}:${dermai.datasource.port}/${dermai.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: ${dermai.datasource.username}
#      password: ${dermai.datasource.password}
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/dermai?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
  redis:
    password: ${dermai.redis.password}
    host: ${dermai.redis.host}
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
    database: 0
    port: 6379

mybatis:
  #mapper config file
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #open camel case
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss

token:
  # jwt
  header: